export const FETCHING_WORKERS = "FETCHING_WORKERS";
export const FETCHED_WORKERS = "FETCHED_WORKERS";
export const FETCHED_WORKERS_FAILURE = "FETCHED_WORKERS_FAILURE";
export const ADD_WORKER = "ADD_WORKER";
export const EDIT_WORKER = "EDIT_WORKER";
export const DELETE_WORKER = "DELETE_WORKER";

export const FETCHING_CLIENTS = "FETCHING_WORKERS";
export const FETCHED_CLIENTS = "FETCHED_CLIENTS";
export const FETCHED_CLIENTS_FAILURE = "FETCHED_CLIENTS_FAILURE";
export const ADD_CLIENT = "ADD_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";

export const FETCHED_TASKS = "FETCHED_TASKS";
export const FETCHING_TASKS_FAILURE = "FETCHED_TASK_FAILURE";
export const ADD_TASK = "ADD_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";

export const FETCHED_PROJECTS = "FETCHED_PROJECTS";
export const FETCHED_PROJECTS_FAILURE = "FETCHED_PROJECTS_FAILURE";
export const ADD_PROJECT = "ADD_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
